apiVersion: batch/v1
kind: CronJob
metadata:
  name: prom-aggregator-cronjob
  namespace: prometheus
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator
            image: burns.azurecr.io/aggregator:v3
            env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: password
            command:
            - node
            - /aggregator.js
            workingDir: /
            volumeMounts:
              - name: config-volume
                mountPath: /config.json
                subPath: config.json
          volumes:
          - name: config-volume
            configMap:
              name: aggregator-config

          restartPolicy: OnFailure