{
 "title": "Long term stats.",
 "description": "Longer term downsampled stats.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "Camera",
     "rawSql": "SELECT timestamp,value FROM TimeSeries.dbo.Series WHERE name='humidity_outside' AND $__timeFilter(timestamp)"
    },
    {
     "dataset": "Camera",
     "rawSql": "SELECT timestamp,value as 'Humidity (Inside)' FROM TimeSeries.dbo.Series WHERE name='humidity_upstairs' AND $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "dataset": "Camera",
     "rawSql": "SELECT timestamp,value*1.8 + 32 as Temperature FROM TimeSeries.dbo.Series WHERE name='temperature_celsius' AND $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Solar Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "Camera",
     "rawSql": "SELECT timestamp,value * 5 as Volts FROM TimeSeries.dbo.Series WHERE name='solar_volts' AND $__timeFilter(timestamp)"
    }
   ]
  }
 ]
}